package com.martiandeveloper.muvlex.utils

const val LANGUAGE_SHARED_PREFERENCE = "LANGUAGE"
const val LANGUAGE_KEY = "language"
const val LANGUAGE_CODE_KEY = "languageCode"
const val VIEWPAGER_PAGES = 3
const val API_KEY = "43031406f2e6f3c3fd2dea56c6fe8367"
const val BASE_URL = "https://api.themoviedb.org/3/"
const val BASE_URL_POSTER = "https://image.tmdb.org/t/p/w185"
const val RATINGS_AND_REVIEW_POLICY_URL =
    "https://github.com/mdismayilov/Muvlex-Privacy-Policy-Terms-Conditions/blob/master/ratings_review_policy.txt"
const val INVALID_EMAIL_FORMAT = "The email address is badly formatted."
const val INVALID_USER =
    "There is no user record corresponding to this identifier. The user may have been deleted."
const val INVALID_PASSWORD =
    "The given password is invalid. [ Password should be at least 6 characters ]"
const val UNVERIFIED_EMAIL = "unverified"
const val EMAIL_ALREADY_EXISTS = "The email address is already in use by another account."
const val WRONG_PASSWORD = "The password is invalid or the user does not have a password."
const val USERNAME_NOT_FOUND = "username_not_found"
const val EMAIL_ALREADY_VERIFIED = "already_verified"
const val USERNAME_NOT_AVAILABLE = "username_not_available"
const val SEND = "send"
const val LOAD = "load"
const val CHECK_USERNAME = "check_username"
const val LOGIN = "login"
const val SAVE = "save"
const val CREATE = "create"
const val SEND_VERIFICATION = "send_verification"
const val GOOGLE_PLAY_SERVICES = "https://policies.google.com/privacy"
const val GOOGLE_ANALYTICS_FOR_FIREBASE = "https://firebase.google.com/policies/analytics"
const val FIREBASE_CRASHLYTICS = "https://firebase.google.com/support/privacy/"
const val FACEBOOK = "https://www.facebook.com/about/privacy/update/printable"
const val APP_EMAIL = "muvlexapp@gmail.com"
const val PRIVACY_POLICY_TEMPLATE_LINK = "https://www.privacypolicytemplate.net/"
const val APP_PRIVACY_POLICY_GENERATOR = "https://app-privacy-policy-generator.nisrulz.com/"
const val ENGLISH = "English"
const val TURKISH = "Türkçe"
const val AZERBAIJANI = "Azəricə"
const val ENGLISH_CODE = "en"
const val TURKISH_CODE = "tr"
const val AZERBAIJANI_CODE = "az"
const val PAGE_SIZE = 20
const val DATE_PATTERN = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
